### ISSUE TITLE
Assertion failure when clearing the database

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dotnet#1204]
A user reported that they see an assertion failure when calling `realm.RemoveAll()`. They navigate to a page that has bindings to realm objects, then navigate back and try to clear the database. The exception is:

```
/Users/realm/workspace/realm_realm-dotnet_PR-1188-6W2R5VDLA4HEBYHVYRS53MBKAKW4RATUW3XSSYGYX3JMUX4SY2YQ/wrappers/src/object-store/src/impl/transact_log_handler.cpp:147: [realm-core-2.3.0] Assertion failed: list.col < list.observer->changes.size()
0   Tyomaarain                          0x0000000102cf3178 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   Tyomaarain                          0x0000000102cf347a _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 506
2   Tyomaarain                          0x0000000102ca1d5c _ZN12_GLOBAL__N_122KVOTransactLogObserver14parse_completeEv + 1512
3   Tyomaarain                          0x0000000102c98263 _ZN5realm5_impl11transaction6cancelERNS_11SharedGroupEPNS_14BindingContextE + 764
4   Tyomaarain                          0x0000000102c95c86 shared_realm_cancel_transaction + 23
5   ???                                 0x000000012c15cb04 0x0 + 5034593028
6   ???                                 0x000000012b32dd55 0x0 + 5019721045
7   ???                                 0x000000012b420165 0x0 + 5020713317
8   ???                                 0x000000012883923c 0x0 + 4974678588
9   ???                                 0x000000012b4c7add 0x0 + 5021399773
10  ???                                 0x00000001297f8464 0x0 + 4991190116
11  ???                                 0x00000001297f60b9 0x0 + 4991180985
12  ???                                 0x000000012b420165 0x0 + 5020713317
13  ???                                 0x000000012883923c 0x0 + 4974678588
14  ???                                 0x000000012b4c7add 0x0 + 5021399773
15  ???                                 0x00000001297f8464 0x0 + 4991190116
16  ???                                 0x00000001297f60b9 0x0 + 4991180985
17  ???                                 0x000000012b420165 0x0 + 5020713317
18  ???                                 0x000000012883923c 0x0 + 4974678588
19  ???                                 0x000000012b4c7add 0x0 + 5021399773
20  ???                                 0x00000001297f8464 0x0 + 4991190116
21  ???                                 0x00000001297f60b9 0x0 + 4991180985
22  ???                                 0x000000012b420165 0x0 + 5020713317
23  ???                                 0x000000012883923c 0x0 + 4974678588
24  ???                                 0x000000012b45331d 0x0 + 5020922653
25  ???                                 0x0000000124079514 0x0 + 4899443988
26  libmonosgen-2.0.dylib               0x000000010e75c927 mono_jit_runtime_invoke + 2183
27  libmonosgen-2.0.dylib               0x000000010e917638 do_runtime_invoke + 88
28  libmonosgen-2.0.dylib               0x000000010e917546 mono_runtime_invoke + 102
29  Tyomaarain                          0x0000000102c0d573 _ZL30native_to_managed_trampoline_9P11objc_objectP13objc_selectorPP11_MonoMethodPKcS7_ + 259
30  Tyomaarain                          0x0000000102c13a6d -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 61
31  Foundation                          0x000000010558ee9e __NSThreadPerformPerform + 326
32  CoreFoundation                      0x000000010e2f5761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
33  CoreFoundation                      0x000000010e2da98c __CFRunLoopDoSources0 + 556
34  CoreFoundation                      0x000000010e2d9e76 __CFRunLoopRun + 918
35  CoreFoundation                      0x000000010e2d9884 CFRunLoopRunSpecific + 420
36  GraphicsServices                    0x000000010f55aa6f GSEventRunModal + 161
37  UIKit                               0x0000000105c12c68 UIApplicationMain + 159
38  ???                                 0x0000000127e5416c 0x0 + 4964303212
39  ???                                 0x0000000127e53ddd 0x0 + 4964302301
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

**Comment by Dids** [comment]
HockeyApp reports this as: `Realms.Exceptions.RealmException: Access to invalidated List object`

More information:
```
at (wrapper managed-to-native) Realms.SynchronizationContextEventLoopSignal+EventLoopPostHandler:wrapper_aot_native (object,intptr)
  at Realms.SynchronizationContextEventLoopSignal+EventLoop+<Post>c__AnonStorey0.<>m__0 (System.Object _) <0x100ebcfc0 + 0x0003b> in <d5e51eda21594574980582845edf3ff0#1e586335933954edea47e57dde13a4d6>:0 
  at UIKit.UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () <0x100c56610 + 0x00027> in <d9a64a30a9e54cff99bd5519750ca6b8#1e586335933954edea47e57dde13a4d6>:0 
  at Foundation.NSAsyncActionDispatcher.Apply () <0x100c737a0 + 0x00023> in <d9a64a30a9e54cff99bd5519750ca6b8#1e586335933954edea47e57dde13a4d6>:0 
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x100c33830 + 0x0002b> in <d9a64a30a9e54cff99bd5519750ca6b8#1e586335933954edea47e57dde13a4d6>:0 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x100c33770 + 0x000ab> in <d9a64a30a9e54cff99bd5519750ca6b8#1e586335933954edea47e57dde13a4d6>:0 
  at Tyomaarain.iOS.Application.Main (System.String[] args) <0x1002c23d0 + 0x00023> in <d56cd661d74e415b9946720dc457050d#1e586335933954edea47e57dde13a4d6>:0
```

**Comment by CrimsonKyle** [comment]
```
/Users/realm/workspace/realm_realm-dotnet_PR-1242-DZBZTX5LYQL5IRKE5BRGKZDOLC4ESNEDLASIPSLRZZVWNHIV3HNQ/wrappers/src/object-store/src/impl/transact_log_handler.cpp:147: [realm-core-2.3.1] Assertion failed: list.col < list.observer->changes.size()
0   AltecService.iOS                    0x001bd580 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 48
1   AltecService.iOS                    0x001bd8fc _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 492
2   AltecService.iOS                    0x00104ba5 _ZN12_GLOBAL__N_122KVOTransactLogObserver14parse_completeEv + 1313
3   AltecService.iOS                    0x001039f7 _ZN5realm11SharedGroup15do_advance_readIN12_GLOBAL__N_122KVOTransactLogObserverEEEbPT_NS_9VersionIDERNS_5_impl7HistoryE + 435
4   AltecService.iOS                    0x000faa18 _ZN5realm5_impl11transaction7advanceERKNSt3__110unique_ptrINS_11SharedGroupENS2_14default_deleteIS4_EEEEPNS_14BindingContextERNS0_15NotifierPackageE + 423
5   AltecService.iOS                    0x000f3329 _ZN5realm5_impl16RealmCoordinator16advance_to_readyERNS_5RealmE + 285
6   AltecService.iOS                    0x00135f43 _ZN5realm5Realm6notifyEv + 209
7   AltecService.iOS                    0x001193d2 _ZNK5realm5_impl17WeakRealmNotifier8CallbackclEv + 46
8   ???                                 0x26a67480 0x0 + 648443008
9   ???                                 0x26a67ea9 0x0 + 648445609
10  ???                                 0x26a67e25 0x0 + 648445477
11  ???                                 0x26100313 0x0 + 638583571
12  ???                                 0x1ee56ae7 0x0 + 518351591
13  libmonosgen-2.0.dylib               0x0b412b8d mono_jit_runtime_invoke + 1485
14  libmonosgen-2.0.dylib               0x0b5f348d do_runtime_invoke + 93
15  libmonosgen-2.0.dylib               0x0b5f3393 mono_runtime_invoke + 115
16  AltecService.iOS                    0x0005186a _Z30native_to_managed_trampoline_9P11objc_objectP13objc_selectorPP11_MonoMethodPKcS7_ + 314
17  AltecService.iOS                    0x0005857a -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 74
18  libobjc.A.dylib                     0x0bb261b9 -[NSObject performSelector:withObject:] + 59
19  Foundation                          0x00af4cb1 __NSThreadPerformPerform + 330
20  CoreFoundation                      0x0afc3edf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
21  CoreFoundation                      0x0afa7fa7 __CFRunLoopDoSources0 + 519
22  CoreFoundation                      0x0afa7434 __CFRunLoopRun + 1124
23  CoreFoundation                      0x0afa6d5b CFRunLoopRunSpecific + 395
24  CoreFoundation                      0x0afa6bbb CFRunLoopRunInMode + 123
25  GraphicsServices                    0x0c16cb4c GSEventRunModal + 177
26  GraphicsServices                    0x0c16c9c7 GSEventRun + 80
27  UIKit                               0x00f83ff3 UIApplicationMain + 148
28  ???                                 0x21443940 0x0 + 558119232
29  ???                                 0x214436c8 0x0 + 558118600
30  ???                                 0x2143d304 0x0 + 558093060
31  ???                                 0x2143cf74 0x0 + 558092148
32  ???                                 0x2143d181 0x0 + 558092673
33  libmonosgen-2.0.dylib               0x0b412b8d mono_jit_runtime_invoke + 1485
34  libmonosgen-2.0.dylib               0x0b5f348d do_runtime_invoke + 93
35  libmonosgen-2.0.dylib               0x0b5f6b56 do_exec_main_checked + 150
36  libmonosgen-2.0.dylib               0x0b5f5ae9 mono_runtime_run_main_checked + 73
37  libmonosgen-2.0.dylib               0x0b489d07 mono_jit_exec + 311
38  libxamarin-debug.dylib              0x0b897c24 xamarin_main + 3380
39  AltecService.iOS                    0x000dd461 main + 113
40  libdyld.dylib                       0x0c60b799 start + 1
IMPORTANT: if you see this error, please send this log to help@realm.io.2017-02-21 11:32:48.758 AltecService.iOS[92973:759464] critical: Stacktrace:

2017-02-21 11:32:48.758 AltecService.iOS[92973:759464] critical:   at <unknown> <0xffffffff>
2017-02-21 11:32:48.759 AltecService.iOS[92973:759464] critical:   at (wrapper managed-to-native) object.wrapper_native_0x11962a (intptr) <0x00012>
2017-02-21 11:32:48.759 AltecService.iOS[92973:759464] critical:   at Realms.SynchronizationContextEventLoopSignal/EventLoop/<Post>c__AnonStorey0.<>m__0 (object) [0x0001e] in <6a4aad7d9c894b85a92bb1ef490f2e66>:0
2017-02-21 11:32:48.759 AltecService.iOS[92973:759464] critical:   at UIKit.UIKitSynchronizationContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3985/9d6e1ab1/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24
2017-02-21 11:32:48.762 AltecService.iOS[92973:759464] critical:   at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/3985/9d6e1ab1/source/xamarin-macios/src/Foundation/NSAction.cs:163
2017-02-21 11:32:48.762 AltecService.iOS[92973:759464] critical:   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <54e129cad3ee4c61a6b46c3680ddc69a>:0
2017-02-21 11:32:48.763 AltecService.iOS[92973:759464] critical:   at <unknown> <0xffffffff>
2017-02-21 11:32:48.763 AltecService.iOS[92973:759464] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <0x00015>
2017-02-21 11:32:48.763 AltecService.iOS[92973:759464] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Users/builder/data/lanes/3985/9d6e1ab1/source/xamarin-macios/src/UIKit/UIApplication.cs:79
2017-02-21 11:32:48.763 AltecService.iOS[92973:759464] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x00038] in /Users/builder/data/lanes/3985/9d6e1ab1/source/xamarin-macios/src/UIKit/UIApplication.cs:63
2017-02-21 11:32:48.764 AltecService.iOS[92973:759464] critical:   at AltecService.iOS.Application.Main (string[]) [0x00008] in /Users/kmrichar/Documents/Git/altec-service/iOS/Main.cs:12
2017-02-21 11:32:48.764 AltecService.iOS[92973:759464] critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <4c55ce78269348cab9604280b9760377>:0
2017-02-21 11:32:48.764 AltecService.iOS[92973:759464] critical: 
Native stacktrace:

2017-02-21 11:32:48.766 AltecService.iOS[92973:759464] critical: 	0   libmonosgen-2.0.dylib               0x0b4ca0ed mono_handle_native_sigsegv + 317
2017-02-21 11:32:48.766 AltecService.iOS[92973:759464] critical: 	1   libmonosgen-2.0.dylib               0x0b525911 sigabrt_signal_handler + 161
2017-02-21 11:32:48.766 AltecService.iOS[92973:759464] critical: 	2   libsystem_platform.dylib            0x0c93cebb _sigtramp + 43
2017-02-21 11:32:48.766 AltecService.iOS[92973:759464] critical: 	3   ???                                 0xffffffff 0x0 + 4294967295
2017-02-21 11:32:48.767 AltecService.iOS[92973:759464] critical: 	4   libsystem_c.dylib                   0x0c6b111f abort + 141
2017-02-21 11:32:48.767 AltecService.iOS[92973:759464] critical: 	5   AltecService.iOS                    0x001bd12b please_report_this_error_to_help_at_realm_dot_io + 11
2017-02-21 11:32:48.767 AltecService.iOS[92973:759464] critical: 	6   AltecService.iOS                    0x001bd679 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 297
2017-02-21 11:32:48.767 AltecService.iOS[92973:759464] critical: 	7   AltecService.iOS                    0x001bd8fc _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 492
2017-02-21 11:32:48.768 AltecService.iOS[92973:759464] critical: 	8   AltecService.iOS                    0x00104ba5 _ZN12_GLOBAL__N_122KVOTransactLogObserver14parse_completeEv + 1313
2017-02-21 11:32:48.768 AltecService.iOS[92973:759464] critical: 	9   AltecService.iOS                    0x001039f7 _ZN5realm11SharedGroup15do_advance_readIN12_GLOBAL__N_122KVOTransactLogObserverEEEbPT_NS_9VersionIDERNS_5_impl7HistoryE + 435
2017-02-21 11:32:48.768 AltecService.iOS[92973:759464] critical: 	10  AltecService.iOS                    0x000faa18 _ZN5realm5_impl11transaction7advanceERKNSt3__110unique_ptrINS_11SharedGroupENS2_14default_deleteIS4_EEEEPNS_14BindingContextERNS0_15NotifierPackageE + 423
2017-02-21 11:32:48.768 AltecService.iOS[92973:759464] critical: 	11  AltecService.iOS                    0x000f3329 _ZN5realm5_impl16RealmCoordinator16advance_to_readyERNS_5RealmE + 285
2017-02-21 11:32:48.769 AltecService.iOS[92973:759464] critical: 	12  AltecService.iOS                    0x00135f43 _ZN5realm5Realm6notifyEv + 209
2017-02-21 11:32:48.769 AltecService.iOS[92973:759464] critical: 	13  AltecService.iOS                    0x001193d2 _ZNK5realm5_impl17WeakRealmNotifier8CallbackclEv + 46
2017-02-21 11:32:48.769 AltecService.iOS[92973:759464] critical: 	14  ???                                 0x26a67480 0x0 + 648443008
2017-02-21 11:32:48.769 AltecService.iOS[92973:759464] critical: 	15  ???                                 0x26a67ea9 0x0 + 648445609
2017-02-21 11:32:48.769 AltecService.iOS[92973:759464] critical: 	16  ???                                 0x26a67e25 0x0 + 648445477
2017-02-21 11:32:48.770 AltecService.iOS[92973:759464] critical: 	17  ???                                 0x26100313 0x0 + 638583571
2017-02-21 11:32:48.770 AltecService.iOS[92973:759464] critical: 	18  ???                                 0x1ee56ae7 0x0 + 518351591
2017-02-21 11:32:48.770 AltecService.iOS[92973:759464] critical: 	19  libmonosgen-2.0.dylib               0x0b412b8d mono_jit_runtime_invoke + 1485
2017-02-21 11:32:48.770 AltecService.iOS[92973:759464] critical: 	20  libmonosgen-2.0.dylib               0x0b5f348d do_runtime_invoke + 93
2017-02-21 11:32:48.771 AltecService.iOS[92973:759464] critical: 	21  libmonosgen-2.0.dylib               0x0b5f3393 mono_runtime_invoke + 115
2017-02-21 11:32:48.771 AltecService.iOS[92973:759464] critical: 	22  AltecService.iOS                    0x0005186a _Z30native_to_managed_trampoline_9P11objc_objectP13objc_selectorPP11_MonoMethodPKcS7_ + 314
2017-02-21 11:32:48.771 AltecService.iOS[92973:759464] critical: 	23  AltecService.iOS                    0x0005857a -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 74
2017-02-21 11:32:48.771 AltecService.iOS[92973:759464] critical: 	24  libobjc.A.dylib                     0x0bb261b9 -[NSObject performSelector:withObject:] + 59
2017-02-21 11:32:48.771 AltecService.iOS[92973:759464] critical: 	25  Foundation                          0x00af4cb1 __NSThreadPerformPerform + 330
2017-02-21 11:32:48.772 AltecService.iOS[92973:759464] critical: 	26  CoreFoundation                      0x0afc3edf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
2017-02-21 11:32:48.772 AltecService.iOS[92973:759464] critical: 	27  CoreFoundation                      0x0afa7fa7 __CFRunLoopDoSources0 + 519
2017-02-21 11:32:48.772 AltecService.iOS[92973:759464] critical: 	28  CoreFoundation                      0x0afa7434 __CFRunLoopRun + 1124
2017-02-21 11:32:48.772 AltecService.iOS[92973:759464] critical: 	29  CoreFoundation                      0x0afa6d5b CFRunLoopRunSpecific + 395
2017-02-21 11:32:48.773 AltecService.iOS[92973:759464] critical: 	30  CoreFoundation                      0x0afa6bbb CFRunLoopRunInMode + 123
2017-02-21 11:32:48.773 AltecService.iOS[92973:759464] critical: 	31  GraphicsServices                    0x0c16cb4c GSEventRunModal + 177
2017-02-21 11:32:48.773 AltecService.iOS[92973:759464] critical: 	32  GraphicsServices                    0x0c16c9c7 GSEventRun + 80
2017-02-21 11:32:48.773 AltecService.iOS[92973:759464] critical: 	33  UIKit                               0x00f83ff3 UIApplicationMain + 148
2017-02-21 11:32:48.773 AltecService.iOS[92973:759464] critical: 	34  ???                                 0x21443940 0x0 + 558119232
2017-02-21 11:32:48.774 AltecService.iOS[92973:759464] critical: 	35  ???                                 0x214436c8 0x0 + 558118600
2017-02-21 11:32:48.774 AltecService.iOS[92973:759464] critical: 	36  ???                                 0x2143d304 0x0 + 558093060
2017-02-21 11:32:48.774 AltecService.iOS[92973:759464] critical: 	37  ???                                 0x2143cf74 0x0 + 558092148
2017-02-21 11:32:48.774 AltecService.iOS[92973:759464] critical: 	38  ???                                 0x2143d181 0x0 + 558092673
2017-02-21 11:32:48.774 AltecService.iOS[92973:759464] critical: 	39  libmonosgen-2.0.dylib               0x0b412b8d mono_jit_runtime_invoke + 1485
2017-02-21 11:32:48.775 AltecService.iOS[92973:759464] critical: 	40  libmonosgen-2.0.dylib               0x0b5f348d do_runtime_invoke + 93
2017-02-21 11:32:48.775 AltecService.iOS[92973:759464] critical: 	41  libmonosgen-2.0.dylib               0x0b5f6b56 do_exec_main_checked + 150
2017-02-21 11:32:48.775 AltecService.iOS[92973:759464] critical: 	42  libmonosgen-2.0.dylib               0x0b5f5ae9 mono_runtime_run_main_checked + 73
2017-02-21 11:32:48.775 AltecService.iOS[92973:759464] critical: 	43  libmonosgen-2.0.dylib               0x0b489d07 mono_jit_exec + 311
2017-02-21 11:32:48.775 AltecService.iOS[92973:759464] critical: 	44  libxamarin-debug.dylib              0x0b897c24 xamarin_main + 3380
2017-02-21 11:32:48.776 AltecService.iOS[92973:759464] critical: 	45  AltecService.iOS                    0x000dd461 main + 113
2017-02-21 11:32:48.776 AltecService.iOS[92973:759464] critical: 	46  libdyld.dylib                       0x0c60b799 start + 1
2017-02-21 11:32:48.776 AltecService.iOS[92973:759464] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by CrimsonKyle** [comment]
Not sure if these are related

**Comment by AndyDentFree** [comment]
I've got a similar case 100% reproducible in an extended sample from QuickJournal so am drilling down to debug.

**Comment by Dids** [comment]
With the latest Realm, this is no longer crashing for me.

**Comment by AndyDentFree** [comment]
@Dids by _latest Realm_ do you mean the 1.0.4 NuGet release?

**Comment by Dids** [comment]
@AndyDentFree Yeah, 1.0.4 Nuget.

**Comment by AndyDentFree** [comment]
In that case my 100% replicable crash hack on QuickJournal is a separate issue :-(

But, always happy to hear someone's problems were fixed.

**Comment by Dids** [comment]
Since mine was more about holding on to RealmObject references, in a view that was no longer visible, it could've been a Xamarin Forms issue too, which has been fixed, hard to tell. :)

**Comment by CrimsonKyle** [comment]
So I no longer am having a assertion failure crash on any of my async write transactions after realm 1.1.0 update, but am still getting assertion failure with "RemoveAll"

**Comment by CrimsonKyle** [comment]
I spoke too soon:

```
/Users/realm/workspace/realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ/wrappers/src/object-store/src/impl/transact_log_handler.cpp:147: [realm-core-2.3.2] Assertion failed: list.col < list.observer->changes.size()
0   AltecService.iOS                    0x002574f0 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 48
1   AltecService.iOS                    0x0025786c _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 492
2   AltecService.iOS                    0x0019d635 _ZN12_GLOBAL__N_122KVOTransactLogObserver14parse_completeEv + 1313
3   AltecService.iOS                    0x0019c487 _ZN5realm11SharedGroup15do_advance_readIN12_GLOBAL__N_122KVOTransactLogObserverEEEbPT_NS_9VersionIDERNS_5_impl7HistoryE + 435
4   AltecService.iOS                    0x00193428 _ZN5realm5_impl11transaction7advanceERKNSt3__110unique_ptrINS_11SharedGroupENS2_14default_deleteIS4_EEEEPNS_14BindingContextERNS0_15NotifierPackageE + 423
5   AltecService.iOS                    0x0018bb4b _ZN5realm5_impl16RealmCoordinator16advance_to_readyERNS_5RealmE + 285
6   AltecService.iOS                    0x001cea47 _ZN5realm5Realm6notifyEv + 209
7   AltecService.iOS                    0x001b2112 _ZNK5realm5_impl17WeakRealmNotifier8CallbackclEv + 46
8   ???                                 0x2cb624a8 0x0 + 750134440
9   ???                                 0x2cb62d69 0x0 + 750136681
10  ???                                 0x2cb44d6d 0x0 + 750013805
11  ???                                 0x27dedee3 0x0 + 668917475
12  ???                                 0x20fcd867 0x0 + 553441383
13  libmonosgen-2.0.dylib               0x0b496b9d mono_jit_runtime_invoke + 1485
14  libmonosgen-2.0.dylib               0x0b67749d do_runtime_invoke + 93
15  libmonosgen-2.0.dylib               0x0b6773a3 mono_runtime_invoke + 115
16  AltecService.iOS                    0x00101ade _Z31native_to_managed_trampoline_11P11objc_objectP13objc_selectorPP11_MonoMethodj + 286
17  AltecService.iOS                    0x0010c8c5 -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 69
18  libobjc.A.dylib                     0x0bbaa1b9 -[NSObject performSelector:withObject:] + 59
19  Foundation                          0x029b5cb1 __NSThreadPerformPerform + 330
20  CoreFoundation                      0x0b047edf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
21  CoreFoundation                      0x0b02bfa7 __CFRunLoopDoSources0 + 519
22  CoreFoundation                      0x0b02b434 __CFRunLoopRun + 1124
23  CoreFoundation                      0x0b02ad5b CFRunLoopRunSpecific + 395
24  CoreFoundation                      0x0b02abbb CFRunLoopRunInMode + 123
25  GraphicsServices                    0x0c1f0b4c GSEventRunModal + 177
26  GraphicsServices                    0x0c1f09c7 GSEventRun + 80
27  UIKit                               0x00e5bff3 UIApplicationMain + 148
28  ???                                 0x2138ff48 0x0 + 557383496
29  ???                                 0x2138fcd0 0x0 + 557382864
30  ???                                 0x2138990c 0x0 + 557357324
31  ???                                 0x2138957c 0x0 + 557356412
32  ???                                 0x21389789 0x0 + 557356937
33  libmonosgen-2.0.dylib               0x0b496b9d mono_jit_runtime_invoke + 1485
34  libmonosgen-2.0.dylib               0x0b67749d do_runtime_invoke + 93
35  libmonosgen-2.0.dylib               0x0b67ab66 do_exec_main_checked + 150
36  libmonosgen-2.0.dylib               0x0b679af9 mono_runtime_run_main_checked + 73
37  libmonosgen-2.0.dylib               0x0b50dd17 mono_jit_exec + 311
38  libxamarin-debug.dylib              0x0b91bbb4 xamarin_main + 3380
39  AltecService.iOS                    0x00175a71 main + 113
40  libdyld.dylib                       0x0c68f799 start + 1
IMPORTANT: if you see this error, please send this log to help@realm.io.2017-03-03 10:59:56.644 AltecService.iOS[72181:600249] critical: Stacktrace:

2017-03-03 10:59:56.644 AltecService.iOS[72181:600249] critical:   at <unknown> <0xffffffff>
2017-03-03 10:59:56.644 AltecService.iOS[72181:600249] critical:   at (wrapper managed-to-native) object.wrapper_native_0x1b230a (intptr) <0x00012>
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at Realms.SynchronizationContextEventLoopSignal/EventLoop/<Post>c__AnonStorey0.<>m__0 (object) [0x0001e] in <c979c5cbb46a42fe8aa1787deaf9c8b7>:0
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at UIKit.UIKitSynchronizationContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4466/c3b39f23/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/4466/c3b39f23/source/xamarin-macios/src/Foundation/NSAction.cs:163
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <54e129cad3ee4c61a6b46c3680ddc69a>:0
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at <unknown> <0xffffffff>
2017-03-03 10:59:56.645 AltecService.iOS[72181:600249] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <0x00015>
2017-03-03 10:59:56.646 AltecService.iOS[72181:600249] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Users/builder/data/lanes/4466/c3b39f23/source/xamarin-macios/src/UIKit/UIApplication.cs:79
2017-03-03 10:59:56.646 AltecService.iOS[72181:600249] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x00038] in /Users/builder/data/lanes/4466/c3b39f23/source/xamarin-macios/src/UIKit/UIApplication.cs:63
2017-03-03 10:59:56.646 AltecService.iOS[72181:600249] critical:   at AltecService.iOS.Application.Main (string[]) [0x00008] in /Users/kmrichar/Documents/Git/altec-service/iOS/Main.cs:12
2017-03-03 10:59:56.646 AltecService.iOS[72181:600249] critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <010c9b4bac4f4e1db9546009e68bec25>:0
2017-03-03 10:59:56.646 AltecService.iOS[72181:600249] critical: 
```

**Comment by nirinchev** [comment]
We're migrating to a new approach to object notifications that should hopefully resolve this issue: #1316.

**Comment by CrimsonKyle** [comment]
@nirinchev I will volunteer to run all our tests against the pre-release version! :)

**Comment by UKDeveloper99** [comment]
I think I'm running in to this error when I call my logout routine, which replaces the entire view stack with my login view controller, exiting the _current view_. It also calls `_realm.RemoveAll()`. The _current view_ is a standard table view bound to a live realm list. I've got the pre-release nuget I'm think, that @nirinchev linked to me via the Xamarin #realm slack channel is that the right one? Still getting the same assertion _access to invalidated list object_.

**Comment by UKDeveloper99** [comment]
Call Stack:
```
Realm.dll!Realms.NativeException.ThrowIfNecessary(System.Func<Realms.Exceptions.RealmExceptionCodes,System.Exception> overrider = (null)) in 
Realm.dll!Realms.ListHandle.GetObjectAtIndex(int index = 0) in 
Realm.dll!Realms.RealmCollectionBase<FaradayAppV2.Core.DataModels.EntryChart>.get_Item(int index = 0) in 
Realm.dll!Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart>.get_Item(int index = 0) in 
mscorlib.dll!System.Reflection.MonoMethod.InternalInvoke() in 
mscorlib.dll!System.Reflection.MonoProperty.GetValue( obj = Value not available,  invokeAttr = Value not available,  binder = Value not available,  index = Value not available,  culture = Value not available) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.8.0.175/src/mono/mcs/class/corlib/System.Reflection/MonoProperty.cs:420
mscorlib.dll!System.Reflection.MonoProperty.GetValue( obj = Value not available,  index = Value not available) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.8.0.175/src/mono/mcs/class/corlib/System.Reflection/MonoProperty.cs:405
MvvmCross.Binding.dll!MvvmCross.Binding.Bindings.Source.Chained.MvxChainedSourceBinding.UpdateChildBinding() in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Chained\MvxChainedSourceBinding.cs:76
MvvmCross.Binding.dll!MvvmCross.Binding.Bindings.Source.Chained.MvxChainedSourceBinding.OnBoundPropertyChanged() in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\Chained\MvxChainedSourceBinding.cs:98
MvvmCross.Binding.dll!MvvmCross.Binding.Bindings.Source.MvxPropertyInfoSourceBinding.SourcePropertyChanged(Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart> sender = {Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart>}, System.ComponentModel.PropertyChangedEventArgs e = {System.ComponentModel.PropertyChangedEventArgs}) in D:\git\MvvmCross\MvvmCross\Core\Binding\Bindings\Source\MvxPropertyInfoSourceBinding.cs:88
mscorlib.dll!System.Reflection.MonoMethod.InternalInvoke() in 
MvvmCross.Platform.dll!MvvmCross.Platform.WeakSubscription.MvxWeakEventSubscription<System.ComponentModel.INotifyPropertyChanged,System.ComponentModel.PropertyChangedEventArgs>.OnSourceEvent(Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart> sender = {Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart>}, System.ComponentModel.PropertyChangedEventArgs e = {System.ComponentModel.PropertyChangedEventArgs}) in D:\git\MvvmCross\MvvmCross\Platform\Platform\WeakSubscription\MvxWeakEventSubscription.cs
Realm.dll!Realms.RealmCollectionBase<FaradayAppV2.Core.DataModels.EntryChart>.RaisePropertyChanged() in 
Realm.dll!Realms.RealmCollectionBase<FaradayAppV2.Core.DataModels.EntryChart>.OnChange(Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart> sender = {Realms.RealmList<FaradayAppV2.Core.DataModels.EntryChart>}, Realms.ChangeSet change = {Realms.ChangeSet}, System.Exception error = (null)) in 
Realm.dll!Realms.RealmCollectionBase<FaradayAppV2.Core.DataModels.EntryChart>.Realms.NotificationsHelper.INotifiable.NotifyCallbacks(Realms.NotifiableObjectHandleBase.CollectionChangeSet? changes = {Realms.NotifiableObjectHandleBase.CollectionChangeSet}, Realms.NativeException? exception = null) in 
Realm.dll!Realms.NotificationsHelper.NotificationCallbackImpl(System.IntPtr managedHandle = 0x16b, System.IntPtr changes = 0x16fd70df8, System.IntPtr exception = 0x0) in 
Realm.dll!Realms.SynchronizationContextEventLoopSignal.EventLoopPostHandler.Invoke() in 
Realm.dll!Realms.SynchronizationContextEventLoopSignal.EventLoop.Post.AnonymousMethod__0(object _ = (null)) in 
```

**Comment by UKDeveloper99** [comment]
Well I managed to workaround the exception by calling `_realm.RemoveAll<EntryChart>()` before `_realm.RemoveAll()`. The `EntryChart` object is used as a child object in the main parent object `Report`. Reports are the `RealmObjects` that are bound to the list. However I'm getting some much weirder behavior now. Upon logging back in... which will start populating the empty database again. I'm getting Realm the error, Realm is already in a WriteTransaction. I always use the same Realm instance on the same thread, the main ui thread. I don't update anything on the background thread.  It feels like the Realm is stuck in a write transaction after the `_realm.RemoveAll()` has failed.

**Comment by UKDeveloper99** [comment]
I believe I've found a separate issue as well, which could be related, I've narrowed it down quite consistently to MvvmCross bindings to a child item in a parent object. The child being part of an `IList<ChildItem> ChildItems { get; }`. It seems to freak out on anything that has a binding to one of those items. Example:

`set.Bind(_imageChart1ViewLoader).For(imageLoader => imageLoader.ImageUrl).To(vm => vm.Report.EntryCharts[0].Url);`

Results in a `System.Reflection.TargetInvocationException`, looks like the binding is still trying to retrieve the object even after the database has been cleared. I tried `BindingContext.ClearAllBindings()` before calling the logout routine but this doesn't seem to help. Without knowing the inner workings of MvvmCross it's hard to say what the exact issue is. But regardless I feel there is certainly some problems with `_realm.RemoveAll()` that need resolving.

**Comment by nirinchev** [comment]
The original issue should have been fixed with the new notification system. If anyone else runs into that assertion, please open a new one so we can investigate separately.
