### ISSUE TITLE
The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly

### ISSUE THREAD

**Issue by Dids** [realm/realm-dotnet#1265]
#### Goal

I'm trying to build my Xamarin.Forms project on Windows, using Visual Studio 2017 and targeting iOS, so building happens on a remote macOS installation.

#### Expected Results

App builds fine, just like it does in Xamarin Studio.

#### Actual Results

All iOS builds (debug/release/simulator/device) fail with the following, even after reinstalling Realm nuget package.

```
Realm.Database.targets(16,5): error MSB4018: The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly.
Realm.Database.targets(16,5): error MSB4018: System.Exception: Realm is referenced by your project but was not found in C:\Users\didan\Work\MyApp\iOS\bin\iPhoneSimulator\Debug\. Make sure that CopyLocal is set to True and try again.
Realm.Database.targets(16,5): error MSB4018:    at RealmBuildTasks.WeaveRealmAssembly.WeaveAssembly(String name, AssemblyDefinition currentAssembly)
Realm.Database.targets(16,5): error MSB4018:    at RealmBuildTasks.WeaveRealmAssembly.Execute()
Realm.Database.targets(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
Realm.Database.targets(16,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

#### Steps & Code to Reproduce

In my case, the project was created in Xamarin Studio. It's a Xamarin.Forms project, targeting both iOS and Android.

Compiling in Xamarin Studio works fine, but as soon as I switch to Visual Studio 2017, the reference error is thrown.

Do note that both Realm and Realm.Database have the "Copy Local" option set to "true", like they should.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Xamarin/Visual Studio version: v2.3.3.193 / Visual Studio 2017 (Release)

Which operating system version and device: Windows 10, macOS Sierra and iPhone/iPhone Simulator

**Comment by Dids** [comment]
As a sidenote, the directory `C:\Users\didan\Work\MyApp\iOS\bin\iPhoneSimulator\Debug\` is empty.

**Comment by UKDeveloper99** [comment]
Had this exact same issue today.

**Comment by nirinchev** [comment]
There is a bug with 1.1.0 that prevents compilation on Visual Studio for iOS. The only workarounds are to revert to 1.0.4 or build using Xamarin Studio.

**Comment by UKDeveloper99** [comment]
I'm still getting this error when updating from Realm v1.0.4 to v1.1.1.

```
Target WeaveRealmAssemblyTarget:
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly.
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: System.Exception: Realm is referenced by your project but was not found in /Users/marksilver/Documents/Workspace/SaltApp/iOS/SaltApp.iOS/bin/iPhone/Debug/. Make sure that CopyLocal is set to True and try again.
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at RealmBuildTasks.WeaveRealmAssembly.WeaveAssembly (System.String name, Mono.Cecil.AssemblyDefinition currentAssembly) [0x0005d] in <7abb78d191b54429a1d8c7260a756093>:0 
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at RealmBuildTasks.WeaveRealmAssembly.Execute () [0x0003d] in <7abb78d191b54429a1d8c7260a756093>:0 
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x0002a] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/msbuild-15.0/src/XMakeBuildEngine/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:632 
    /Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x002bf] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/msbuild-15.0/src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
Done building target "WeaveRealmAssemblyTarget" in project "SaltApp.iOS.csproj" -- FAILED.

Done building project "SaltApp.iOS.csproj" -- FAILED.

Build FAILED.

Storyboards/MessageInbox.storyboard : ibtool warning : “View Controller“ is unreachable because it has no entry points, and no identifier for runtime access via -[UIStoryboard instantiateViewControllerWithIdentifier:].
/Users/marksilver/Documents/Workspace/SaltApp/iOS/SaltApp.iOS/obj/iPhone/Debug/device-builds/iphone9.4-10.2.1/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcons" has an unassigned child.
/Users/marksilver/Documents/Workspace/SaltApp/iOS/SaltApp.iOS/obj/iPhone/Debug/device-builds/iphone9.4-10.2.1/actool/cloned-assets/Assets.xcassets : actool warning : The file "Icon-Small-ipad@2x.png" for the image set "AppIcons" does not exist.
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1980,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
MvxCustom/MvxAnimatedTableViewSource.cs(60,8): warning CS0108: `SaltApp.iOS.MvxAnimatedTableViewSource<T>.TryDoAnimatedChange(System.Collections.Specialized.NotifyCollectionChangedEventArgs)' hides inherited member `MvvmCross.Binding.iOS.Views.MvxTableViewSource.TryDoAnimatedChange(System.Collections.Specialized.NotifyCollectionChangedEventArgs)'. Use the new keyword if hiding was intended
AppDelegate.cs(206,4): warning CS0618: `UIKit.UIAlertView.UIAlertView(string, string, UIKit.UIAlertViewDelegate, string, params string[])' is obsolete: `Use overload with a IUIAlertViewDelegate parameter'
AppDelegate.cs(223,21): warning CS0168: The variable `e' is declared but never used
AppDelegate.cs(310,23): warning CS0168: The variable `e' is declared but never used
AppDelegate.cs(185,35): warning CS0168: The variable `e' is declared but never used
AppDelegate.cs(191,23): warning CS0168: The variable `e' is declared but never used
AppDelegate.cs(406,22): warning CS0168: The variable `e' is declared but never used
AppDelegate.cs(443,22): warning CS0168: The variable `e' is declared but never used
LinkerPleaseInclude.cs(101,58): warning CS0219: The variable `test' is assigned but its value is never used
Views/AdviserView.cs(103,21): warning CS0168: The variable `e' is declared but never used
Views/LoginView.cs(20,26): warning CS0169: The private field `SaltApp.iOS.LoginView._tapRecognizer' is never used
Views/PreferencesPersonalView.cs(20,21): warning CS0169: The private field `SaltApp.iOS.PreferencesPersonalView._textFieldDelegate' is never used
Views/PreferencesContactView.cs(60,32): warning CS0414: The private field `SaltApp.iOS.PreferencesContactView.TableSource._viewModel' is assigned but its value is never used
Views/RecommendationsDetailView.cs(20,46): warning CS0414: The private field `SaltApp.iOS.RecommendationsDetailView._imageViewLoaders' is assigned but its value is never used
Views/Cells/AdviserThreadCellView.cs(17,39): warning CS0169: The private field `SaltApp.iOS.AdviserThreadCellView._imageViewLoader' is never used
Views/AdviserInboxDetailView.cs(21,12): warning CS0414: The private field `SaltApp.iOS.AdviserInboxDetailView._keyboardShowNotification' is assigned but its value is never used
Views/AdviserInboxDetailView.cs(22,12): warning CS0414: The private field `SaltApp.iOS.AdviserInboxDetailView._keyboardHideNotification' is assigned but its value is never used
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly.
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER.
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018: System.Exception: Realm is referenced by your project but was not found in /Users/marksilver/Documents/Workspace/SaltApp/iOS/SaltApp.iOS/bin/iPhone/Debug/. Make sure that CopyLocal is set to True and try again.
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at RealmBuildTasks.WeaveRealmAssembly.WeaveAssembly (System.String name, Mono.Cecil.AssemblyDefinition currentAssembly) [0x0005d] in <7abb78d191b54429a1d8c7260a756093>:0 
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at RealmBuildTasks.WeaveRealmAssembly.Execute () [0x0003d] in <7abb78d191b54429a1d8c7260a756093>:0 
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x0002a] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/msbuild-15.0/src/XMakeBuildEngine/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:632 
/Users/marksilver/.nuget/packages/realm.database/1.1.1/build/Realm.Database.targets(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x002bf] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/msbuild-15.0/src/XMakeBuildEngine/BackEnd/Components/RequestBuilder/TaskBuilder.cs:787 
```

**Comment by nirinchev** [comment]
Can you verify that your realm references are marked as `Copy Local`? Additionally, did you restart XS after the upgrade - it sometimes caches stuff which could result in the incorrect binary for the task being picked up. If none of that works, would you be willing to share your project privately so we can investigate?

**Comment by UKDeveloper99** [comment]
One moment.

**Comment by UKDeveloper99** [comment]
Fixed:

I use project.json (nuget v3) in my projects. I added this line to the .csproj file     `<CopyNuGetImplementations>true</CopyNuGetImplementations>` which has resolved the issue.

**Comment by nirinchev** [comment]
Happy to hear it's working now and thanks for letting us know what the fix in that case is - I'm sure it will help others as well :)

**Comment by mbrookson** [comment]
Not sure why this is closed as it is still an issue. I've updated to `Realm.Database.1.2.1` and `Realm.DataBinding.1.1.0`, and like @nirinchev mentioned above, it only works for now in Xamarin Studio but _not_ in the new v1 Visual Studio for Mac. Since Xamarin Studio now has a popup to get people switching to Visual Studio, I would say this issue should remain open?

**Comment by nirinchev** [comment]
The cause of this issue was found and addressed. If you're experiencing similar or new problems, please open a new ticket so we can investigate.

**Comment by mbrookson** [comment]
I receive the exact error message `The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly` if I build my project with the new _stable_ Visual Studio release for Mac, Mono 5.0 and the above mentioned packages, however it works in Xamarin Studio. I would have assumed it is the same issue?

**Comment by mbrookson** [comment]
Never mind... was just the programs keeping multiple versions of Nuget packages in the packages folder and getting confused!

Working fine! Oops.
