### ISSUE TITLE
User metadata is encrypted everywhere, not just on Apple

### ISSUE THREAD

**Issue by RZiegler979** [realm/realm-dotnet#1967]
## Goals

I am trying to import data from a realm server in a .NET Framework windows service. 

## Expected Results

Login to the Realm server exactly as documentation instructs and retrieve a local copy of the data.

## Actual Results

Error on LoginAsync: "Metadata Realm encryption was specified, but no encryption key was provided"

## Steps to Reproduce

Create windows service project in VS 2019 using .NET Framework 4.6.1, 

## Code Sample

 ```
var credentials = Credentials.UsernamePassword(RealmConnectionInfo.Username, RealmConnectionInfo.Password, false);
var admin = await Realms.Sync.User.LoginAsync(credentials, new Uri(RealmConnectionInfo.LoginUri));
Uri u = new Uri(RealmConnectionInfo.Uri);
var config = new FullSyncConfiguration(u, admin, RealmConnectionInfo.LocalPath);
config.ClientResyncMode = ClientResyncMode.Manual;
config.IsDynamic = false;

using (var realm = Realm.GetInstance(config))
{
    await realm.GetSession().WaitForDownloadAsync();
    ...
    ...
}
```

## Version of Realm and Tooling
Realm Cloud, v3.28.2
Windows 10
.NET Framework 4.6.1 or 4.7.2(I have tried both)
Realm Nuget Package 4.3.0 or 4.2.0(I have rolled back and still get the error)

I cannot post the full project publicly due to company guidelines but I will provide any extra information needed in email directly if requested. I want to also note that there are extra lines in this code example that are not called for in documentation. Specifically:
```
config.ClientResyncMode = ClientResyncMode.Manual;
config.IsDynamic = false;
```
and:
```
await realm.GetSession().WaitForDownloadAsync();
```

Those lines were put in place after three months of being unable to retrieve data from the server and getting no response on any support channels. The project worked for about a month until this latest update. However they are not the source of this problem as the program throws the exception at LoginAsync and never makes it to any of those lines.

**Comment by fealebenpae** [comment]
This is a 4.3.0 bug, unfortunately. You need to do a complete clean of your project (delete `bin` and `obj` folders) for NuGet to correctly update the native libraries included in your project when you're downgrading.

You can either downgrade to 4.2.0 (if you clean your project), or work around this by calling `Realms.Sync.SyncConfigurationBase.Configure(Realm.Sync.UserPersistenceMode.NotEncrypted)` at the start of your application. This should be the default behavior on non-Apple platforms, but due to a bug user metadata encryption is forced even on platforms where it's not automatically applicable.

**Comment by VagueGit** [comment]
The workaround calling `SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted)` at the start of the application resolved [#1960](https://github.com/realm/realm-dotnet/issues/1960)

**Comment by VagueGit** [comment]
As an alternative, are there docs on how to migrate realms from unencrypted to encrypted in DotNET?

**Comment by fealebenpae** [comment]
@VagueGit could you elaborate?
The encryption here deals with the user metadata in Sync - like the IDs of logged-in users, for example, which are persisted across application launches. Realm files themselves have an entirely separate form of encryption which can be toggled by setting `RealmConfigurationBase.EncryptionKey` when opening a realm file for the first time.

**Comment by RZiegler979** [comment]
@fealebenpae 
Well, this silenced the error that was occurring on LoginAsync, unfortunately it now just crashes silently on the Login line. I did have to use:
`SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted);`
the command you provided threw an error stating that Realm did not contain a definition for Sync. Probably just a typo for Realm instead of Realms.

**Comment by fealebenpae** [comment]
@RZiegler979 can you try to uninstall your app from the device and then deploying again? This should get rid of the cached metadata.

**Comment by RZiegler979** [comment]
@fealebenpae I'm just running a solution in VS 2019. I deleted the bin and obj and rebuilt, but I don't have an app installed. I cleaned the solution and rebuilt as well, If there is metadata stored elsewhere I will need a path to what I need to delete manually. I have not tried downgrading to 4.2.0 yet and will do that momentarily. I was attempting to work around 4.3.0 issues first.

**Comment by fealebenpae** [comment]
If you're running directly on your Windows machine (let's say in a Console or WPF app) then you should delete the `realm-object-server` folder in your `Documents` user folder - it contains the local copies of the synchronized realms, as well as the `io.realm.object-server-utility` folder that contains the actual user metadata.

In an Android, iOS, or UWP app this folder is stored inside the application sandbox so uninstalling the app clears it out automatically.

**Comment by RZiegler979** [comment]
Deleted everything you listed. As well as bin and obj folders. Downgraded to 4.2.0. Still silent crash on loginasync.

Windows project. As a side note, even after deleting bin and obj folders and downgrading to 4.2 I still get the metadata encryption error if I comment out the `SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted);`
So either the problem is server based or I am missing something when trying to delete everything and downgrade to 4.2

Thank you for all the help though.

**Comment by fealebenpae** [comment]
I'm sorry to hear you're still having troubles with that. If you're up for it, [enabling native code debugging](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-in-mixed-mode?view=vs-2019#enable-mixed-mode-debugging-for-a-managed-calling-app) in Visual Studio should catch the crash in `LoginAsync` and hopefully even show a stacktrace or exception message.

**Comment by VagueGit** [comment]
@fealebenpae as encrypted realms are now the default, perhaps Realm docs should include guidance on migrating unencrypted realms to encrypted.

Also there was no mention of this as a breaking change in the release notes.

We released our app in preview mode when Realm Cloud was first released. We used unencrypted Realms for simplicity. However we now have many users who have migrated their businesses from the release version of our app (not Realm) to the preview version on Realm Cloud, so we need guidance on how to migrate these realms from unencrypted to encrypted.

If necessary we can wait until we migrate to Atlas if that simplifies things.

**Comment by fealebenpae** [comment]
Hey @VagueGit, I'm afraid there might be some misunderstanding around this bug.

We're not touching encryption of realm files. They are still not encrypted by default, unless the developer sets `RealmConfigurationBase.EncryptionKey`. There is no need to migrate from not encrypted to encrypted or anything like that.

The data we're talking about encrypting here the user metadata - basically the contents of `User.AllLoggedIn` which are persisted across app launches in the `realm-object-server/io.realm.object-server-utility` folder. That's what this big is about. Definitely not the contents of any realm files, synchronized or local.

The user metadata has always been encrypted by default on iOS and macOS devices, where Realm uses the system Keychain APIs to store a randomly-generated encryption key. On the iOS Simulator, Android, and everywhere else where a Keychain API equivalent does not exist or cannot be used we do not encrypt it - instead the developer has the ability, via `SyncConfigurationBase.Initialize()` to provide a custom encryption key for securing the user metadata or to disable user metadata caching altogether. The nature of this bug is that since the 4.3.0 release Realm decided it can encrypt the user metadata _everywhere_ and not just on iOS and macOS devices. Again, actual realm files are not impacted by this at all. An application that upgraded to 4.3.0 and which does not use any Sync functionality will happily continue working, for example, regardless of platform.

I hope this clear things up. I'm happy to elaborate some more if you have questions.

**Comment by VagueGit** [comment]
> 
> 
> This is a 4.3.0 bug, unfortunately. You need to do a complete clean of your project (delete `bin` and `obj` folders) for NuGet to correctly update the native libraries included in your project when you're downgrading.
> 
> You can either downgrade to 4.2.0 (if you clean your project), or work around this by calling `Realms.Sync.SyncConfigurationBase.Initialize(Realm.Sync.UserPersistenceMode.NotEncrypted)` at the start of your application. This should be the default behavior on non-Apple platforms, but due to a bug user metadata encryption is forced even on platforms where it's not automatically applicable.

I followed these instructions to workaround because in [1960](https://github.com/realm/realm-dotnet/issues/1960) @fealebenpae said
> 
> 
> The user metadata for logged-in users (usernames, server addresses, UUIDs) is encrypted by default - this is unrelated from whether the realms you use are encrypted or not. It seems this is related to the same underlying problem as #1956.

[1960](https://github.com/realm/realm-dotnet/issues/1960) still hasn't been marked as a bug

**Comment by RZiegler979** [comment]
I did as you suggested and checked the box for native code debugging. Unfortunately I still get a silent crash with no error message on LoginAsync. I have deleted the bin and obj folders, as well as the realm-object-server folder. I have tried downgrading to 4.2.0. Unfortunately none of this has made a difference. Setting `SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted);` silenced the metadata encryption key not provided error but it still crashes on the same line.

**Comment by fealebenpae** [comment]
Can you try to create a new project that logs in to the same server?

**Comment by pfedotovsky** [comment]
The correct workaround is

```
// workaround for https://github.com/realm/realm-dotnet/issues/1967
if (Device.RuntimePlatform != Device.iOS)
{
   SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted);
}
```

`SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted); `crashes on iOS so 'if' is required.
